events {}

http {
  include /etc/nginx/mime.types;
  sendfile on;
  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend:8000/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /postback {
      proxy_pass http://backend:8000/postback;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend:80/;
    }
  }
}
